/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ../common/Shop.xml -i ../common/datasets/Product.h -p ShopInterface
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "ShopInterface.h"

/*
 * Implementation of interface class ComScythestudioDbusShopInterface
 */

ComScythestudioDbusShopInterface::ComScythestudioDbusShopInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComScythestudioDbusShopInterface::~ComScythestudioDbusShopInterface()
{
}

