/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ../common/Shop.xml -i ../common/datasets/Product.h -a ShopAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SHOPADAPTOR_H
#define SHOPADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "../common/datasets/Product.h"
#include <QtCore/qcontainerfwd.h>

/*
 * Adaptor class for interface com.scythestudio.dbus.shop
 */
class ShopAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.scythestudio.dbus.shop")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.scythestudio.dbus.shop\">\n"
"    <method name=\"addProduct\">\n"
"      <arg direction=\"in\" type=\"(is)\" name=\"product\"/>\n"
"      <annotation value=\"Product\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"getProducts\">\n"
"      <arg direction=\"out\" type=\"a(is)\"/>\n"
"      <annotation value=\"QList&lt;Product&gt;\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <signal name=\"productAdded\">\n"
"      <arg direction=\"out\" type=\"(is)\"/>\n"
"      <annotation value=\"Product\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    ShopAdaptor(QObject *parent);
    virtual ~ShopAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void addProduct(Product product);
    QList<Product> getProducts();
Q_SIGNALS: // SIGNALS
    void productAdded(Product in0);
};

#endif
